### PR TITLE
Added support for .NetStandard 1.6 so it can run on AspNetCore

### LINKED ISSUE #36: Support for ASPNetCore 1.0.1
i'm trying to get my web api project in aspnetcore (.netCoreApp, version 1.0) working with halcyon, but importing Halcyon.Mvc v2.1.0 gives following error: 

Package Halcyon.Mvc 2.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Halcyon.Mvc 2.1.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - net46 (.NETFramework,Version=v4.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

### PR DESCRIPTION
**Pull request by mkeymolen**
this pull request fixes #36

### CODE REVIEW

**Comment by samuelabj** [comment]
Thanks

**Comment by samuelabj** [comment]
Sorry looks like there's a problem with the build

**Comment by mkeymolen** [comment]
@samuelabj , can you please push a new package to nuget?

**Comment by samuelabj** [comment]
Done

**Pull request merged**
